### ISSUE TITLE
The feature names were wrong

### ISSUE THREAD

**Issue by Emily-Jiang** [OpenLiberty/guide-mongodb-intro#122]
The feature versions in the following statements were out of date.

> 
The features that are required to create the CDI producer for MongoDB are [Contexts and Dependency Injection](https://openliberty.io/docs/latest/reference/feature/cdi-2.0.html) (cdi-2.0), [Secure Socket Layer](https://openliberty.io/docs/latest/reference/feature/ssl-1.0.html) (ssl-1.0), [MicroProfile Config](https://openliberty.io/docs/latest/reference/feature/mpConfig-1.4.html) (mpConfig-1.4), and [Password Utilities](https://openliberty.io/docs/latest/reference/feature/passwordUtilities-1.0.html) (passwordUtilities-1.0).

**Comment by gkwan-ibm** [comment]
close
- issue was addressed
