### ISSUE TITLE
Dev Content Review 6

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guide-mongodb-intro#19]
- [x] Need Additional Prereq section for Docker and Mongodb
  - after Getting started section
- **The MongoDB configuration**
  - [ ] I doubt that using /etc (/etc/mongodb) is the practice
- **The Dockerfile**
  - [x] polish the Dockerfile
    - give more space lines
    - add comments to each stage
    - reduce the length of the following line by shorten either ARG name
      - `-subj "/C=$COUNTRY/ST=$STATE_PROVINCE/L=$LOCALITY/O=$ORGANIZATION/OU=$UNIT/CN=$COMMON_NAME"`
  - [x] the second stage description is too detail
    - simpify it
- **Server configuration**
  - [x] "The Open Liberty server configuration defines the following settings:" -> "The provide Open Liberty server configuration defines the following settings:"
  - [x] Consider to the section title to "Configuring the Open Liberty server"
    - replace server.xml
- **Creating a CDI Producer for Mongo**
  - **Configuring with MicroProfile Config**
    - [x] need to explain how to get the value of mongo.pass.encoded
- **Basic CRUD operations**
  - [x] change the title to "Creating basic CRUD operations" or "Creating CRUD operations" or "Implementing  CRUD operations"

**Comment by jimmy1wu** [comment]
> The MongoDB configuration
 I doubt that using /etc (/etc/mongodb) is the practice

The mongo docker image docs (https://hub.docker.com/_/mongo) uses the `/etc/mongo` folder to store the configuration file. i put the certs, data, and other files & folders in there too so they are all in one place. 

Based on the mongodb docs, the folders they use are `/var/log/mongodb/` for system log, `/data/db/` for data, and `/etc/ssl/` for certificates.

Do you prefer to put the files in a single folder for convenience, or follow what they are doing in docs? 

@gkwan-ibm

**Comment by gkwan-ibm** [comment]
- [x] In my understanding, `/etc` should be used for configuration (and somewhere for `logs`). I agree to use a single place to do all 3 config, log, and data, but not under `/etc`.
- [x] in Dockerfile, suggest to use other word for ST instead of PROVINCE
  - `ST=$PROVINCE`
- [ ] move "Getting started" after "Setting up MongoDB"
- [ ] move "Try what you’ll build" as a subsection under  "Getting started"
- **Configuring the Open Liberty Server**
  - [x] Need a to explain what this section is doing and navigate to the start directory
  - [x] because the dev mode is not started, better Create instead of Replace
  - [x] the following sentence and the points may need to be rewritten (as our general practice to explain what we are doing in the file) 
      - "The provided Open Liberty server configuration defines the following settings:"
      - some points may not need to explain, e.g. `<httpEndpoint/>`, `<webApplication/>`,
      - focus on whatever specific for the monogo db and the application required 
- **Starting the Open Liberty server in development mode**
  - [x] navigate statement may not need (move to  **Configuring the Open Liberty Server**)
- [x] rewrite **Using an encoded password with passwordUtilities-1.0** section including the title
  - use `PasswordUtil.passwordEncode("openliberty", "aes");` not practical
  - because dev mode is started, users can go to target/liberty/wlp/bin/ directory and run `./securityUtility encode thePassword --encoding=aes` to generate the encoded password
- **Using TLS**
  - [x] rewrite the paragraph to explain MongoProducer first then explain how sslContext from

**Comment by jimmy1wu** [comment]
> move "Getting started" after "Setting up MongoDB"

cannot be moved after `setting up mongodb`  since user has to clone the repo in `getting started` to get the the config file and setup script is inside the repo

>move "Try what you’ll build" as a subsection under "Getting started"

cannot move `try what you'll build` under `getting started` since the user first needs to clone the repo in `getting started` and then do the `setting up mongodb` section before they can try it out

**Comment by gkwan-ibm** [comment]
@jimmy1wu 

- **Adding the truststore to the Open Liberty Server**
  - [x] Add a statement to explain why copy truststore.p12 
- **Configuring with MicroProfile Config**
  - [x] "Additionally, the user’s `username` and `password` are set here. "
    - The hotspot `password` does not hightlight the `mongo.pass.encoded` property
  - [x]  "Copy the output and replace `openliberty` with the encoded password." 
    - The hotspot `openliberty` does not hightlight the `mongo.pass.encoded` property
    - Users will easily make mistake. If it possible to show the encoded value at this moment at the right pane? If not, prefer to show the encoded value and reword this statement.
- **Implementing CRUD operations**
  - [x] "The com.mongodb.client package is used ..." Should it be in plural?
