### ISSUE TITLE
Peer review - macOS

### ISSUE THREAD

**Issue by ankitagrawa** [OpenLiberty/guide-mongodb-intro#26]
Peer Review: review to be done by a peer member. 

- [x] Check that the guide has working instructions and sample code
- [x] Check the quality of code according to the best coding practices
- [x] Check the quality and presentation of guide according to [Structure and Style Guideline](https://github.com/OpenLiberty/draft-guides-template/wiki/Guidelines-for-Structure-and-Styles)
- [x] Check the consistency of guide with template and other guides
- [x] Examples with the right outcomes are provided
- [x] Example with the wrong outcomes, if any, are provided
- [x] Check that all licensing statements are properly stated in all files
- [x] Check that the `pom.xml`, `server.xml`, etc files are clean
- [x] Check that the directories are properly structured
- [ ] Test the guide on 3 platforms: Mac, Win, Linux
- [x] If any URL visits, try them on different browsers: Firefox, Chrome, Safari
- [x] If any URL visits, try `curl` command where applicable 
- [x] Ensure that the guide is using the latest version of the `liberty-maven-plugin` or `liberty-gradle-plugin` where applicable
- [x] Check that some of these `page-tags` are used in a guide: `MicroProfile, Maven, Docker, Kubernetes, Gradle, Java EE, Security, Cloud`. Only these tags are visible on the website. Latest list [here](https://github.com/OpenLiberty/openliberty.io/blob/master/src/main/content/_includes/visible-tags.liquid). 
- [ ] Check the `attribution` statement is accurate for the guide
- [ ] Verify the `travisTest.sh` script, if any, is accurate and consistent with other guides

Peer Testing: tests to be done by a peer member.

Guide’s contributor’s (if available, otherwise peer tester’s) responsibility: 
- [ ] Additional tests where applicable: 
  - [ ] Define test coverage and review with team (including guide contributor, if available)
  - [ ] Define detail test cases 
  - [ ] Consider corner cases targeting the specific guide
  - [ ] Consider different platform tests, ie, Mac, Windows, Linux
  - [ ] Consider corner cases UI tests
  - [ ] Consider testing URL on all browsers, ie, FF, Chrome, Safari
  - [ ] Consider testing the `curl` command for URL visits
- [ ] Consider building with both Maven and Gradle build tools 
- [ ] Testing with different IDEs, ie, Atom, Eclipse (Optional: VS.code, IntelliJ, Microclimate)
- [ ] Run Acrolinx Checker on draft (above 70 score approximately)
- [ ] Consider SEO title and description for the guides 
- [ ] Ensure automated test is enable, set up with Travis CI, and able to schedule tests 
- [ ] Run `diff -r start/ finish/` and there's no differences
- [ ] Ensure that the automation tests are able to run when PR is created

Peer Tester’s responsibility: 
- [ ] Check the appearance of the guide on test site for the following items: 
  - [ ] Table of contents 
  - [ ] Headings
  - [ ] Paragraphs
  - [ ] code snippets
  - [ ] outputs
  - [ ] links
  - [ ] hotspots
- [ ] Test the guide end-to-end with working instruction and sample code
- [ ] Perform all the defined test cases

**Comment by ankitagrawa** [comment]
<img width="263" alt="image" src="https://user-images.githubusercontent.com/8294670/80630685-99147f80-8a22-11ea-98a8-a52e1bb1edef.png">

Is there a way to reduce the number of entries bcoz there is a scroll bar coming up.

**Comment by ankitagrawa** [comment]
### What you’ll learn

> The crew members will be stored in MongoDB in JSON documents in this format:

Is there a JSON document or you mean JSON format? When you say JSON document does it have .JSON extension?

> Injecting dependencies into microservices and Separating configuration from code in microservices.

Hyperlink should open in new tab. add `^` to the [^]

**Comment by ankitagrawa** [comment]
**Setting up MongoDB**

> Then, the resulting mongo image will be run in a 

Is be necessary in the statement? Should be Then, the resulting mongo image will  run in a

> The mongodb.conf file specifies the MongoDB configuration the MongoDB daemon 

Statement doesn't look complete. Should be The mongodb.conf file specifies **that** the MongoDB configuration the MongoDB daemon

**Comment by ankitagrawa** [comment]
**Creating a CDI Producer for Mongo**

>  MongoDB 2.X versions

X should be small x.

**Comment by ankitagrawa** [comment]
**Implementing CRUD operations**

> For more information about these packages, see the com.mongodb.client Javadocs and com.mongodb.client.result Javadocs.

should be com.mongodb.client and com.mongodb.client.result Javadocs with Javadocs ommitted from the URL.

**Comment by jimmy1wu** [comment]
@ankitagrawa ready for review

**Comment by ankitagrawa** [comment]
reviewed and approved.
