### ISSUE TITLE
Peer Review - Windows #2

### ISSUE THREAD

**Issue by salmad3** [OpenLiberty/guide-mongodb-intro#27]
Peer Review: review to be done by a peer member. 

Functionality
---
- [x] Check that the guide has working instructions and sample code
- [x] Test the guide on 3 platforms: Mac, **Win**, Linux
- [x] If any URL visits, try them on different browsers: Firefox, Chrome, Safari
- [ ] If any URL visits, try `curl` command where applicable 

Formatting & Presentation
---
- [x] Check the quality of code according to the best coding practices
    - [x] Ensure that command substitutions use the `$(cmd)` format and not ``` `cmd` ```
    - [x] Ensure that the console output of the integrated tests do not include the `[INFO]` tab
- [x] Check the quality and presentation of guide according to [Structure and Style Guideline](https://github.com/OpenLiberty/draft-guides-template/wiki/Guidelines-for-Structure-and-Styles)
- [x] Check the consistency of guide with template and other guides
- [x] Examples with the right outcomes are provided
- [x] Example with the wrong outcomes, if any, are provided
- [x] Check that all licensing statements are properly stated in all files
- [x] Check that the `pom.xml`, `server.xml`, etc files are clean
- [x] Check that the directories are properly structured
- [x] Ensure that the guide is using the latest version of the `liberty-maven-plugin` or `liberty-gradle-plugin` where applicable
- [x] Check that some of these `page-tags` are used in a guide: `MicroProfile, Maven, Docker, Kubernetes, Gradle, Java EE, Security, Cloud`. Only these tags are visible on the website. Latest list [here](https://github.com/OpenLiberty/openliberty.io/blob/master/src/main/content/_includes/visible-tags.liquid). 
- [x] Check the `attribution` statement is accurate for the guide
- [x] Verify the `travisTest.sh` script, if any, is accurate and consistent with other guides

Peer Testing: tests to be done by a peer member.

Guide’s contributor’s (if available, otherwise peer tester’s) responsibility: 
- [x] Additional tests where applicable: 
    - [x] Define test coverage and review with team (including guide contributor, if available)
    - [x] Define detail test cases 
    - [x] Consider corner cases targeting the specific guide
    - [x] Consider different platform tests, ie, Mac, **Windows**, Linux
    - [x] Consider corner cases UI tests
    - [x] Consider testing URL on all browsers, ie, FF, Chrome, Safari
    - [ ] Consider testing the `curl` command for URL visits
- [x] Consider building with both Maven and Gradle build tools 
- [x] Testing with different IDEs, ie, Atom, Eclipse (Optional: VS.code, IntelliJ, Microclimate)
- [x] Run Acrolinx Checker on draft (above 70 score approximately)
- [x] Consider SEO title and description for the guides 
- [x] Ensure automated test is enable, set up with Travis CI, and able to schedule tests 
- [x] Run `diff -r start/ finish/` and there's no differences
- [ ] Ensure that the automation tests are able to run when PR is created

Peer Tester’s responsibility: 
- [x] Check the appearance of the guide on test site for the following items: 
    - [x] Table of contents 
    - [x] Headings
    - [x] Paragraphs
    - [x] code snippets
    - [x] outputs
    - [x] links
    - [x] hotspots 
- [x] Test the guide end-to-end with working instruction and sample code
- [x] Perform all the defined test cases

**Comment by salmad3** [comment]
# Formatting & Presentation
## What you'll learn
- [x] Perhaps: The crew members will be stored in MongoDB in JSON documents, **as shown in the following format:** 
- [x] Perhaps: This microservice connects to MongoDB using TLS **through a CDI producer. This injects** a MongoDatabase and MicroProfile Config to make configuring the MongoDB driver simple.

---
<img width="550" alt="image" src="https://user-images.githubusercontent.com/25497083/80638641-c5ce9400-8a2e-11ea-956e-6461ceec1d56.png">

---

- hyperlinks should open new tabs.
<img width="554" alt="image" src="https://user-images.githubusercontent.com/25497083/80811241-79e92f80-8b93-11ea-9e5d-b8da052268c1.png">

---

## Setting up MongoDB
### Running MongoDB in a Docker container
 - [x] add backticks to 27017
> Execute the following commands to build the image using the Dockerfile, run it in a Docker container, and map port 27017 from the container to your host machine:

### Adding the truststore to the Open Liberty server
- [x] should organize commands to be more presentable.
---
<img width="566" alt="image" src="https://user-images.githubusercontent.com/25497083/80811470-f419b400-8b93-11ea-81b7-4bc0586cb17d.png">

---

### Configuring with MicroProfile Config
- [x] config file already exists in **start**.
---
<img width="547" alt="image" src="https://user-images.githubusercontent.com/25497083/80811595-37742280-8b94-11ea-8b37-4d70741d7ef1.png">

---

**Noticed rest of feedback is repetitive with https://github.com/OpenLiberty/draft-guide-mongodb/issues/28 & https://github.com/OpenLiberty/draft-guide-mongodb/issues/26**

**Comment by jimmy1wu** [comment]
@DannyS03 ready for review

**Comment by salmad3** [comment]
Feedback addressed.
