### ISSUE TITLE
Peer Review (Linux)

### ISSUE THREAD

**Issue by NimG98** [OpenLiberty/guide-mongodb-intro#28]
Peer Review: review to be done by a peer member. 

Functionality
---
- [x] Check that the guide has working instructions and sample code
- [ ] Test the guide on 3 platforms: 
    - [ ] Mac 
    - [ ] Windows 
    - [x] Linux 
- [ ] If any URL visits, try them on different browsers: 
    - [x] Firefox 
    - [x] Chrome 
    - [ ] Safari 
- [ ] If any URL visits, try `curl` command where applicable 

Formatting & Presentation
---
- [x] Check the quality of code according to the best coding practices
    - [x] Ensure that command substitutions use the `$(cmd)` format and not ``` `cmd` ```
    - [x] Ensure that the console output of the integrated tests do not include the `[INFO]` tab
- [x] Check the quality and presentation of guide according to [Structure and Style Guideline](https://github.com/OpenLiberty/draft-guides-template/wiki/Guidelines-for-Structure-and-Styles)
- [x] Check the consistency of guide with template and other guides
- [x] Examples with the right outcomes are provided
- [x] Example with the wrong outcomes, if any, are provided
- [x] Check that all licensing statements are properly stated in all files
- [x] Check that the `pom.xml`, `server.xml`, etc files are clean
- [x] Check that the directories are properly structured
- [x] Ensure that the guide is using the latest version of the `liberty-maven-plugin` or `liberty-gradle-plugin` where applicable
- [x] Check that some of these `page-tags` are used in a guide: `MicroProfile, Maven, Docker, Kubernetes, Gradle, Java EE, Security, Cloud`. Only these tags are visible on the website. Latest list [here](https://github.com/OpenLiberty/openliberty.io/blob/master/src/main/content/_includes/visible-tags.liquid). 
- [x] Check the `attribution` statement is accurate for the guide
- [x] Verify the `travisTest.sh` script, if any, is accurate and consistent with other guides

Peer Testing: tests to be done by a peer member.

Guide’s contributor’s (if available, otherwise peer tester’s) responsibility: 
- [x] Additional tests where applicable: 
    - [x] Define test coverage and review with team (including guide contributor, if available)
    - [x] Define detail test cases 
    - [x] Consider corner cases targeting the specific guide
    - [ ] Consider different platform tests, ie, Mac, Windows, Linux
    - [x] Consider corner cases UI tests
    - [x] Consider testing URL on all browsers, ie, FF, Chrome, Safari
    - [ ] Consider testing the `curl` command for URL visits
- [x] Consider building with both Maven and Gradle build tools 
- [x] Testing with different IDEs, ie, Atom, Eclipse (Optional: VS.code, IntelliJ, Microclimate)
- [ ] Run Acrolinx Checker on draft (above 70 score approximately)
- [x] Consider SEO title and description for the guides 
- [x] Ensure automated test is enable, set up with Travis CI, and able to schedule tests 
- [x] Run `diff -r start/ finish/` and there's no differences
- [x] Ensure that the automation tests are able to run when PR is created

Peer Tester’s responsibility: 
- [x] Check the appearance of the guide on test site for the following items: 
    - [x] Table of contents 
    - [x] Headings
    - [x] Paragraphs
    - [x] code snippets
    - [x] outputs
    - [x] links
    - [x] hotspots 
- [x] Test the guide end-to-end with working instruction and sample code
- [x] Perform all the defined test cases

**Comment by NimG98** [comment]
## What you’ll learn
- [x] hyperlinks don't open in new tab
    - "Injecting dependencies into microservices"
    - "Separating configuration from code in microservices"

## Setting up MongoDB
- [x] add "that" after configuration
    > The `mongodb.conf` file specifies the `MongoDB` configuration the `MongoDB` daemon should use.

## Running MongoDB in a Docker container
- [x] add backticks to `27017`
    > Execute the following commands to build the image using the Dockerfile, run it in a Docker container, and map port 27017 from the container to your host machine:

## Adding the truststore to the Open Liberty server
- [x] the 2 commands here look too messsy since they are long and close together
    ![image](https://user-images.githubusercontent.com/46586499/80628587-8cdaf300-8a1f-11ea-9f42-ef9c61d95be2.png)
    - instead of having one command box:
       maybe have a sentence for the first command, then a command box,
       then another sentence for the second command, then another command box

## Try what you’ll build
- [x] change this section to have the output
    
    ![image](https://user-images.githubusercontent.com/46586499/80633705-32de2b80-8a27-11ea-853e-381cb265be84.png)
    To something like this:
    ![image](https://user-images.githubusercontent.com/46586499/80631087-3b346780-8a23-11ea-8e2a-6422b2b033bf.png)

## Configuring with MicroProfile Config
- [x] it says to Create the configuration file, but the `microprofile-config.properties` already exists in the start dir
- [ ] instead of showing a sample encoded password in the `microprofile-config.properties`: `{aes}APtt+/vYxxPa0jE1rhmZue9wBm3JGqFK3JR4oJdSDGWM1wLr1ckvqkqKjSB2Voty8g==`, just have a placeholder instead, `mongo.pass.encoded=[encoded-password]`

## Creating a CDI Producer for Mongo
- [x] the `createMongo()` hotspot should highlight just the function and not the annotation
    > The `createMongo()` method is annotated with `@Produces` and returns an instance of `MongoClient`.
- [x] i think the hotspot for `MongoClient` should be highlighting the `);` too
    ![image](https://user-images.githubusercontent.com/46586499/80636701-ddf0e400-8a2b-11ea-84aa-2062e1da89aa.png)
- [x] the `createDB()` hotspot should highlight just the function and not the annotation
    > The `createDB()` method is annotated with `@Produces` and returns an instance of `MongoDatabase`.
- [x] i feel like the indentation for these methods look confusing
    ![image](https://user-images.githubusercontent.com/46586499/80637008-50fa5a80-8a2c-11ea-836d-f47be444ec24.png)
    - i get if it was done so that the parameters can be easily hotspot tagged
    - but then maybe change the parameters' indentation to be farther out, so that it's not lined up in the same column as the body of the function
- [x] the `close()` hotspot should highlight just the function and not the annotation
    > The `close()` method is a cleanup function for the `MongoClient`.

## Implementing CRUD operations
- [x] "Creating a RESTful web serivce" hyperlink doesn't open in a new tab
    > See Creating a RESTful web serivce for more information about creating a REST service with JAX-RS, JSON-B, and Open Liberty.
- [x] since you want them to copy and paste this input into the POST, make it a green copy box, instead of a gray box:
    ![image](https://user-images.githubusercontent.com/46586499/80639017-66bd4f00-8a2f-11ea-94bb-b508c537f63d.png)
- [ ] when i check the `GET /api/crew`, it lists members i made during the "Try what you'll build" section too. Is it only supposed to show the Member1 i made in the POST?
- [x] the hotspot for methods `add()`, `retrieve()`, `update()`, `remove()` should just highlight the functions and not the annotations
- [x] this gray output box should not be copyable, since it's an output only:
    ![image](https://user-images.githubusercontent.com/46586499/80640101-f6173200-8a30-11ea-9f2b-27d86e7b6485.png)
    - the output should have `[role="no_copy"]` above it in the readme

## Running the microservice
- [ ] why do we use the openapi ui to GET/POST/PUT/DELETE, and then in this section there is a nicer UI to do the same things. Why can't we just use this nicer UI only?

## Testing the service
- [x] the `testAddCrewMember()`, `testGetCrewMembers()`, `testUpdateCrewMember()`, `testDeleteCrewMember()`
- [x] add "is" before "returned":
    > `testGetCrewMembers()` verifies that a list of crew members returned by the microservice API.

**Comment by NimG98** [comment]
## Other
- [ ] shouldn't the Dockerfile be inside the `start` and `finish` directory, instead of being outside both of those directories
    - [ ] if changing this, then need to modify travisTest.sh too
- [x] `diff -rq finish start` shows differences that can be fixed
    - spacing difference between finish and start for `src/main/java/io/openliberty/guides/application/CrewApplication.java`
- [ ] i think the license for the java files should be `2020` instead of `2018, 2020`
- [x] pom.xml versions:
    - LMP -> 3.2
    - maven-war-plugin -> 3.2.3
    - microprofile -> 3.3
    - junit-jupiter -> 5.6.2
    - both org.apache.cxf -> 3.3.6
- [x] no page tags being shown
    ![image](https://user-images.githubusercontent.com/46586499/80652151-57e19700-8a45-11ea-906f-c85b951e0865.png)

    - to see the page tags being shown, need to add guide under [guide_tags.json](https://github.com/OpenLiberty/guides-common/blob/master/guide_tags.json) on `dev` branch, and then refresh draft site to see the page tags

**Comment by jimmy1wu** [comment]
> instead of showing a sample encoded password in the microprofile-config.properties: {aes}APtt+/vYxxPa0jE1rhmZue9wBm3JGqFK3JR4oJdSDGWM1wLr1ckvqkqKjSB2Voty8g==

just going to show the encoded pass in the guide and leave the command there as reference

> think the license for the java files should be 2020 instead of 2018, 2020

this guide is based on https://github.com/OpenLiberty/sample-mongodb so i append the 2020. correct me if im wrong

> When i check the GET /api/crew, it lists members i made during the "Try what you'll build" section too. Is it only supposed to show the Member1 i made in the POST?

GET /api/crew shows all members in the database. same database instance is used between finish and start

>shouldn't the Dockerfile be inside the start and finish directory, instead of being outside both of those directories

put the dockerfile outside since they use the same db instance for the start and finish and they do not restart it.

>why do we use the openapi ui to GET/POST/PUT/DELETE, and then in this section there is a nicer UI to do the same things. Why can't we just use this nicer UI only?

openapi can show how the endpoints work better since it is more direct. web ui is kind of just a nice to have i guess after you know it all works. http req through openapi prob makes more sense to people too than through javascript

@NimG98 Maybe the last three we have to ask gilbert about. rest of it is ready to review

**Comment by jimmy1wu** [comment]
> When i check the GET /api/crew, it lists members i made during the "Try what you'll build" section too. Is it only supposed to show the Member1 i made in the POST?

> shouldn't the Dockerfile be inside the start and finish directory, instead of being outside both of those directories

> why do we use the openapi ui to GET/POST/PUT/DELETE, and then in this section there is a nicer UI to do the same things. Why can't we just use this nicer UI only?

@gkwan-ibm do you have any comment about about those 3 points?

My thoughts for the points:

1. maybe we can leave a note when they are testing the `GET /api/crew` that the response may contain the crew members they created in the "try what you'll build" section.

2. Leave dockerfile in root or put it in assets folder. Not sure if it is necessary to put it in start and finish folders.

3. i think it's fine as is.

**Comment by gkwan-ibm** [comment]
2. consider to move the Dockerfile under the assets directory. The Dockerfile is used for mongodb container which is used by both start and finish

3. we can use openapi for development purpose. Question is "In the Running the microservice section, we say that GUI is provided and readers can run the app through it"

**Comment by jimmy1wu** [comment]
@NimG98 @gkwan-ibm 

1. added comment to say user might see crew members created in try what you'll build section,
2. moved dockerfile to assets folders
3. since we show gui first and then show openapi, i explained why we are using open api in the CRUD section

https://github.com/OpenLiberty/draft-guide-mongodb/commit/51a7eddfca11fb5deabdca33371770ecf2bad7cc
or view on lgdev

If it's good, i'll make a pr

**Comment by NimG98** [comment]
Feedback addressed
