### ISSUE TITLE
Peer review - macOS

### ISSUE THREAD

**Issue by jj-zhang** [OpenLiberty/guide-mongodb-intro#3]
Peer Review: review to be done by a peer member. 

- [x] Check that the guide has working instructions and sample code
- [x] Check the quality of code according to the best coding practices
- [x] Check the quality and presentation of guide according to [Structure and Style Guideline](https://github.com/OpenLiberty/draft-guides-template/wiki/Guidelines-for-Structure-and-Styles)
- [x] Check the consistency of guide with template and other guides
- [x] Examples with the right outcomes are provided
- [x] Example with the wrong outcomes, if any, are provided
- [x] Check that all licensing statements are properly stated in all files
- [x] Check that the `pom.xml`, `server.xml`, etc files are clean
- [x] Check that the directories are properly structured
- [ ] Test the guide on 3 platforms: Mac, Win, Linux
- [x] If any URL visits, try them on different browsers: Firefox, Chrome, Safari
- [x] If any URL visits, try `curl` command where applicable 
- [x] Ensure that the guide is using the latest version of the `liberty-maven-plugin` or `liberty-gradle-plugin` where applicable
- [x] Check that some of these `page-tags` are used in a guide: `MicroProfile, Maven, Docker, Kubernetes, Gradle, Java EE, Security, Cloud`. Only these tags are visible on the website. Latest list [here](https://github.com/OpenLiberty/openliberty.io/blob/master/src/main/content/_includes/visible-tags.liquid). 
- [ ] Check the `attribution` statement is accurate for the guide
- [ ] Verify the `travisTest.sh` script, if any, is accurate and consistent with other guides

Peer Testing: tests to be done by a peer member.

Guide’s contributor’s (if available, otherwise peer tester’s) responsibility: 
- [x] Additional tests where applicable: 
  - [x] Define test coverage and review with team (including guide contributor, if available)
  - [x] Define detail test cases 
  - [x] Consider corner cases targeting the specific guide
  - [x] Consider different platform tests, ie, Mac, Windows, Linux
  - [x] Consider corner cases UI tests
  - [x] Consider testing URL on all browsers, ie, FF, Chrome, Safari
  - [x] Consider testing the `curl` command for URL visits
- [x] Consider building with both Maven and Gradle build tools 
- [x] Testing with different IDEs, ie, Atom, Eclipse (Optional: VS.code, IntelliJ, Microclimate)
- [x] Run Acrolinx Checker on draft (above 70 score approximately)
- [x] Consider SEO title and description for the guides 
- [x] Ensure automated test is enable, set up with Travis CI, and able to schedule tests 
- [x] Run `diff -r start/ finish/` and there's no differences
- [ ] Ensure that the automation tests are able to run when PR is created

Peer Tester’s responsibility: 
- [x] Check the appearance of the guide on test site for the following items: 
  - [ ] Table of contents 
  - [ ] Headings
  - [ ] Paragraphs
  - [ ] code snippets
  - [ ] outputs
  - [ ] links
  - [ ] hotspots
- [ ] Test the guide end-to-end with working instruction and sample code
- [ ] Perform all the defined test cases

**Comment by jj-zhang** [comment]
## Setting up MongoDB
- [x] Mention the prompt `You are about to be asked to enter information that will be incorporated
into your certificate request.` after generating the certificate.

- [x] Check this line:
> Use the Java keytool to add the certificate to the truststore and replace <<PASSWORD>> with your own password.

You may specify the meaning of `your own password` and may mention setting up the new password and the password is at least 6 characters.

- [x] Should better specify this instruction is for both mongoDB user and Docker user.

> Issue the following commands to enter the mongo Shell, create a new database, and create a new user for the database (replace <<PATH_TO_PEM_FILE>> with the path to the mongodb_tls.pem file):`

- [x] Redundant \` in `mongodb_tls.pem file):``

**Comment by jj-zhang** [comment]
- [x]  link guide to travis-ci.org
- [x] add guide to draft automation tests (in olguides-automation repo)

**Comment by jimmy1wu** [comment]
feedback addressed, closing
