### ISSUE TITLE
Content review

### ISSUE THREAD

**Issue by gljrobinson** [OpenLiberty/guide-mongodb-intro#44]
- TLS —> acronym not explained

- the MongoDB driver is be bundled in your microservice in your pom.xml. —> this sentence doesn’t make sense with the “be” in there

- SSL —> will everyone know what the accronym stands for??

- AES —> what does this stand for?

- Create, Read, Update and Delete —> this titles aren't very descriptive and seem very short for a title of a subsection. Would help if we could add more of a description to them.

-  TDocument type parameter —> what is a Document type parameter?

- The response may include crew members created in the Try what you’ll build section. —> should the “Try what you’ll build” be formatted differently to standard text? A link or some form of special formatting?

**Comment by jimmy1wu** [comment]
@GraceJansen feedback addressed.

PTAL at https://github.com/OpenLiberty/draft-guide-mongodb/pull/46 or http://lgdev1.fyre.ibm.com:4020/guides/mongodb-intro.html

**Comment by yeekangc** [comment]
Additional feedback here: https://github.com/OpenLiberty/draft-guide-mongodb/issues/48.  FYI, @GraceJansen.
