### ISSUE TITLE
Review feedback

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/guide-mongodb-intro#48]
- The guide should focus on accessing and persisting data with MongoDB, a document-based NoSQL database.
    - It shouldn't be a documentation on how to do things with Liberty but a guide on how a developer can work with MongoDB for persistence.

- The guide's content should be revised accordingly.  At least, reorganized accordingly based on the focus or positioning above.  Should dive into the application development aspects of working with MongoDB first or as the focus with configuration aspects and what you need to do for Liberty as secondary (or means to an end).

- Hotspots are done in ways inconsistent with how we do them in other guides.  Regular text shouldn't be marked as hotspots but technical keywords only.  Should rewrite/revise the writing accordingly.  (If inline text needs to be used as hotspots, we will need a different and better design.)

@gkwan-ibm @lauracowen

**Comment by gkwan-ibm** [comment]
@meswan

**Comment by meswan** [comment]
@yeekangc, in order to show data persistence, would it be sufficient to demonstrate:
1. Add a few crew members.
1. Bring down the Liberty server.
1. Start the Liberty server and verify that the crew members added previously are still present.

**Comment by yeekangc** [comment]
I am not sure I fully understand that.  We can discuss what the team has in mind further.

**Comment by gkwan-ibm** [comment]
@meswan, see following recommendations
- update the title to "Persisting data with MongoDB"
  - it will be the main focus of the guide
- update the description and seo title
- the seo description can keep to have CDO and mp config
- **Setting up MongoDB**
  - remove the subsections "The MongoDB configuration" and "The Dockerfile"
  - keep to mention the monogo db and docker web docs to learn more about MongoDB
- Combine the "Configuring the Open Liberty Server", "Starting the Open Liberty server in development mode", and "Configuring with MicroProfile Config" sectons in one. The title can be "Configuring the server". It contains following
  - start dev mode
  - replace server.xml
  - create the microprofile-config.properties
- Rename "Creating a CDI Producer for Mongo" to a better title
  - "Then, the `username`, `database name`, and `decoded password` ..." no need to have hotspots
- Rename "Implementing CRUD operations" to "Performing CRUD operations"
  - same as the JPA guide
  - change the subsection titles to "Creating/Reading/Updating/Deleting data" or with a better generic term
  - "...before `inserting` or `updating` the database." no hotspot for both words
     - may consider to add the method name for hotspots, e.g. "...before inserting  and updating the database by the `add()` and `update()` method respectively."
- Rename "Testing the service" to "Testing the application"
  - same as the JPA guide
- Change hotspots that use English word. Either remove the hotspot or use code. See the above 2 examples

**Comment by meswan** [comment]
- [x] - update the title to "Persisting data with MongoDB"
- [ ]   - it will be the main focus of the guide
- [x] - update the description and seo title
- [x] - the seo description can keep to have CDO and mp config
- [x] - **Setting up MongoDB**
- [x]   - remove the subsections "The MongoDB configuration" and "The Dockerfile"
- [x]   - keep to mention the monogo db and docker web docs to learn more about MongoDB
- [x] - Combine the "Configuring the Open Liberty Server", "Starting the Open Liberty server in development mode", and "Configuring with MicroProfile Config" sectons in one. The title can be "Configuring the server". It contains following
- [x]   - start dev mode
- [ ]   - replace server.xml
- [x]   - create the microprofile-config.properties
- [x] - Rename "Creating a CDI Producer for Mongo" to a better title
- [x]   - "Then, the `username`, `database name`, and `decoded password` ..." no need to have hotspots
- [x] - Rename "Implementing CRUD operations" to "Performing CRUD operations"
- [ ]   - same as the JPA guide
- [x]   - change the subsection titles to "Creating/Reading/Updating/Deleting data" or with a better generic term
- [x]   - "...before `inserting` or `updating` the database." no hotspot for both words
- [ ]      - may consider to add the method name for hotspots, e.g. "...before inserting  and updating the database by the `add()` and `update()` method respectively."
- [x] - Rename "Testing the service" to "Testing the application"
- [ ]   - same as the JPA guide
- [ ] - Change hotspots that use English word. Either remove the hotspot or use code. See the above 2 examples
