### ISSUE TITLE
Peer review - Linux

### ISSUE THREAD

**Issue by ankitagrawa** [OpenLiberty/guide-mongodb-intro#5]
Peer Review: review to be done by a peer member. 

- [ ] Check that the guide has working instructions and sample code
- [ ] Check the quality of code according to the best coding practices
- [ ] Check the quality and presentation of guide according to [Structure and Style Guideline](https://github.com/OpenLiberty/draft-guides-template/wiki/Guidelines-for-Structure-and-Styles)
- [ ] Check the consistency of guide with template and other guides
- [ ] Examples with the right outcomes are provided
- [ ] Example with the wrong outcomes, if any, are provided
- [ ] Check that all licensing statements are properly stated in all files
- [ ] Check that the `pom.xml`, `server.xml`, etc files are clean
- [ ] Check that the directories are properly structured
- [ ] Test the guide on 3 platforms: Mac, Win, Linux
- [ ] If any URL visits, try them on different browsers: Firefox, Chrome, Safari
- [ ] If any URL visits, try `curl` command where applicable 
- [ ] Ensure that the guide is using the latest version of the `liberty-maven-plugin` or `liberty-gradle-plugin` where applicable
- [ ] Check that some of these `page-tags` are used in a guide: `MicroProfile, Maven, Docker, Kubernetes, Gradle, Java EE, Security, Cloud`. Only these tags are visible on the website. Latest list [here](https://github.com/OpenLiberty/openliberty.io/blob/master/src/main/content/_includes/visible-tags.liquid). 
- [ ] Check the `attribution` statement is accurate for the guide
- [ ] Verify the `travisTest.sh` script, if any, is accurate and consistent with other guides

Peer Testing: tests to be done by a peer member.

Guide’s contributor’s (if available, otherwise peer tester’s) responsibility: 
- [ ] Additional tests where applicable: 
  - [ ] Define test coverage and review with team (including guide contributor, if available)
  - [ ] Define detail test cases 
  - [ ] Consider corner cases targeting the specific guide
  - [ ] Consider different platform tests, ie, Mac, Windows, Linux
  - [ ] Consider corner cases UI tests
  - [ ] Consider testing URL on all browsers, ie, FF, Chrome, Safari
  - [ ] Consider testing the `curl` command for URL visits
- [ ] Consider building with both Maven and Gradle build tools 
- [ ] Testing with different IDEs, ie, Atom, Eclipse (Optional: VS.code, IntelliJ, Microclimate)
- [ ] Run Acrolinx Checker on draft (above 70 score approximately)
- [ ] Consider SEO title and description for the guides 
- [ ] Ensure automated test is enable, set up with Travis CI, and able to schedule tests 
- [ ] Run `diff -r start/ finish/` and there's no differences
- [ ] Ensure that the automation tests are able to run when PR is created

Peer Tester’s responsibility: 
- [ ] Check the appearance of the guide on test site for the following items: 
  - [ ] Table of contents 
  - [ ] Headings
  - [ ] Paragraphs
  - [ ] code snippets
  - [ ] outputs
  - [ ] links
  - [ ] hotspots
- [ ] Test the guide end-to-end with working instruction and sample code
- [ ] Perform all the defined test cases

**Comment by ankitagrawa** [comment]
**What you’ll learn**

"This microservice connects to MongoDB using TLS by using a CDI producer to inject a MongoDatabase and MicroProfile Config to make configuring MongoDB driver simple."

End should be like to make MongoDb driver configuration simple

**Setting up MongoDB**

Getting error while creating private key

`openssl req -x509 -newkey rsa:2048 -nodes -days 365 -keyout assets/security/private.key -out assets/security/cert.pem
Generating a 2048 bit RSA private key
.+++
............................+++
writing new private key to 'assets/security/private.key'
assets/security/private.key: No such file or directory
4569034348:error:0EFFF06C:configuration file routines:CRYPTO_internal:no value:/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-47.11.1/libressl-2.8/crypto/conf/conf_lib.c:322:group=req name=default_bits
4569034348:error:02FFF002:system library:func(4095):No such file or directory:/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-47.11.1/libressl-2.8/crypto/bio/bss_file.c:255:fopen('assets/security/private.key', 'w')
4569034348:error:20FFF002:BIO routines:CRYPTO_internal:system lib:/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-47.11.1/libressl-2.8/crypto/bio/bss_file.c:257:
`

**Comment by ankitagrawa** [comment]
**Setting up MongoDB**

after docker run 
docker run --name mongo-sample -v assets:/etc/mongodb -p 127.0.0.1:27017:27017 -d mongo --config /etc/mongodb/security/mongodb_tls.conf


docker exec -it mongo-sample bash 
is giving error 

[root@pontine1 draft-guide-mongodb]# docker run --name mongo-sample -v assets:/etc/mongodb -p 127.0.0.1:27017:27017 -d mongo --config /etc/mongodb/security/mongodb_tls.conf
26aed61bcdac12671092f1309f41b68ebcb7e4d8693ca7a0335e2ab6073d90a0
[root@pontine1 draft-guide-mongodb]# docker exec -it mongo-sample bash
Error response from daemon: Container 26aed61bcdac12671092f1309f41b68ebcb7e4d8693ca7a0335e2ab6073d90a0 is not running

**Comment by ankitagrawa** [comment]
**Try what you’ll build**

1) Before this Check out the microservice at the http://localhost:9080/mongo URL.

you should write something that in console you would see "The MongoServer server is ready to run a smarter planet. The MongoServer server started" which illustrates the service is ready for use

2) Check out the microservice at the http://localhost:9080/mongo URL.
you should show a sample output. What would developer see when they hit the service.

I used curl and didn't see any response.

**Comment by ankitagrawa** [comment]
**Creating a CDI Producer for Mongo**

1) Create the MongoProducer class.
src/main/java/io/openliberty/guides/mongo/MongoProducer.java

There is no mongo directory in the start directory. can you please rectify it.

**Comment by ankitagrawa** [comment]
**Configuring with MicroProfile Config**

Create the configuration file.
src/main/webapp/META-INF/microprofile-config.properties

File already exists. May be you wanna modify the text?

**Comment by ankitagrawa** [comment]
**Basic CRUD operations**

1) The com.mongodb.client package is used help to implement : Text is incorrect. Needs to be corrected

2) Seeing errors while making changes to the code.

`[INFO] [ERROR   ] CWWKO1650E: Validation of the OpenAPI document produced the following error(s): 
[INFO]                                                                                                                
[INFO]  - Message: The Path Item Object must contain a valid path. The "PUT" operation of the "/crew/{id}" path does not define a path parameter that is declared: "id", Location: #/paths/~1crew~1{id}
[INFO]  - Message: The Path Item Object must contain a valid path. The "POST" operation of the "/crew/{id}" path does not define a path parameter that is declared: "id", Location: #/paths/~1crew~1{id}
[INFO]  - Message: The Path Item Object must contain a valid path. The "DELETE" operation of the "/crew/{id}" path does not define a path parameter that is declared: "id", Location: #/paths/~1crew~1{id}
[INFO] 
[INFO] [AUDIT   ] CWWKT0016I: Web application available (default_host): http://172.17.0.1:9080/mongo/
[INFO] [AUDIT   ] CWWKZ0003I: The application guide-mongodb-intro updated in 1.469 seconds.
[INFO] [AUDIT   ] CWWKT0017I: Web application removed (default_host): http://172.17.0.1:9080/mongo/
[INFO] [AUDIT   ] CWWKZ0009I: The application guide-mongodb-intro has stopped successfully.
`

<img width="1637" alt="image" src="https://user-images.githubusercontent.com/8294670/72102008-f493f380-32f3-11ea-900c-4cfdd98ab195.png">


3) The retrieve() method handle : 
Hotspot not working.

4) Code indentation needs to be fixed for all 4 methods.

**Comment by ankitagrawa** [comment]
**Testing the service**

1)  server and pointing a web browser at the http://localhost:9080/mongo URL. A
Phrase the sentence properly.

2)method is indicated with the @Test annotation
Instead of indicated it should be annotated.

3) No test directory
Create the CrewApplicationEndpointIT class.
src/test/java/it/io/openliberty/guides/application/CrewApplicationEndpointIT.java

Need to add .gitkeep to the directory.

**Comment by jimmy1wu** [comment]
feedback addressed, closing
